export type Language = 'es' | 'en';

export const UI = {
  brand: 'ACCIONABLES',
  language: {
    heading: 'AI Adoption Self-Assessment',
    subtitle:
      "Find out exactly where you stand - and what the top 3% of professionals are already doing that you probably aren't.",
    meta: '15 quick-tap questions · ~2 minutes. No overthinking.',
    es: 'Español',
    en: 'English',
  },
  quiz: {
    es: {
      levelOf: (n: number) => `Nivel ${n} de 5`,
      questionOf: (x: number, total: number) => `Pregunta ${x} de ${total}`,
      yes: 'SÍ',
      no: 'NO',
      back: '← Pregunta anterior',
    },
    en: {
      levelOf: (n: number) => `Level ${n} of 5`,
      questionOf: (x: number, total: number) => `Question ${x} of ${total}`,
      yes: 'YES',
      no: 'NO',
      back: '← Previous question',
    },
  },
  results: {
    es: {
      affirmativeLabel: 'Respuestas afirmativas',
      scoreOf: (s: number, t: number) => `${s} de ${t}`,
      nextStepHeading: 'Tu siguiente paso',
      benchmarkTitle: 'Compara tus resultados',
      benchmarkSubtitle: 'Responde 3 preguntas rápidas para ver cómo te comparas con la comunidad.',
      benchmarkCta: 'Comparar con la comunidad',
      again: 'Hacer el quiz de nuevo',
      ctaHeading: '¿Qué sigue?',
      ctaBody: 'Descubre cómo se compara tu nivel con el de otros profesionales de tu industria.',
      emailMeButton: 'Enviarme por correo',
      emailMeSending: 'Enviando…',
      emailMeSent: '¡Enviado!',
      emailMeError: 'No pudimos enviarlo. Intenta de nuevo.',
    },
    en: {
      affirmativeLabel: 'Affirmative answers',
      scoreOf: (s: number, t: number) => `${s} of ${t}`,
      nextStepHeading: 'Your next step',
      benchmarkTitle: 'See how you compare',
      benchmarkSubtitle:
        'Answer 3 quick questions to see how your score stacks up against the community.',
      benchmarkCta: 'Compare with the community',
      again: 'Take the quiz again',
      ctaHeading: "What's next?",
      ctaBody: 'Find out how your level compares to other professionals in your industry.',
      emailMeButton: 'Email this to me',
      emailMeSending: 'Sending…',
      emailMeSent: 'Sent!',
      emailMeError: "Couldn't send. Try again.",
    },
  },
  comingSoon: {
    es: {
      title: '¡Muchas gracias!',
      body: 'Tu aporte es muy valioso. Estamos recopilando respuestas y en cuanto tengamos suficientes, publicaremos los resultados del benchmark aquí mismo y te los enviaremos por email.',
      shareHeading: 'Mientras tanto, ayúdanos a correr la voz',
      shareBody: 'Cuantas más personas participen, mejores serán los resultados para todos.',
      shareCta: 'Copiar enlace para compartir',
      shareCopied: '¡Enlace copiado!',
    },
    en: {
      title: 'Thank you so much!',
      body: "Your input means a lot. We're collecting responses and as soon as we have enough, we'll publish benchmark results right here and send them to you by email.",
      shareHeading: 'In the meantime, help us spread the word',
      shareBody: 'The more people participate, the better the results are for everyone.',
      shareCta: 'Copy link to share',
      shareCopied: 'Link copied!',
    },
  },
  valueProp: {
    es: {
      heading: 'Terminaste. Esto es lo que pasa ahora.',
      sub1: 'Tu nivel de adopción de IA está listo.',
      sub2: 'Pero antes de mostrártelo — hay algo más valioso que podemos ofrecerte.',
      card1Title: 'Tus resultados, en tu correo',
      card1Desc: 'Análisis completo de tu nivel + próximos pasos',
      card2Title: 'Ve dónde estás vs. todos los demás',
      card2Desc: 'Compara tu puntaje con profesionales en tu país, industria y tipo de empresa',
      cta: 'Ver mis resultados + benchmark',
      skip: 'Saltar — solo muéstrame mi puntaje',
      liveCounter: (n: number) =>
        `Únete a ${n.toLocaleString()} profesionales que ya midieron su nivel de IA.`,
    },
    en: {
      heading: "You finished. Here's what happens next.",
      sub1: 'Your AI adoption level is ready.',
      sub2: "But before we show you — there's something more valuable we can offer you.",
      card1Title: 'Your results, sent to your inbox',
      card1Desc: 'Full breakdown of your level + next steps',
      card2Title: 'See where you stand vs. everyone else',
      card2Desc:
        'Compare your score against professionals in your country, industry, and company type',
      cta: 'Get my results + benchmark',
      skip: 'Skip — just show me my score',
      liveCounter: (n: number) =>
        `Join ${n.toLocaleString()} professionals who've already benchmarked their AI level.`,
    },
  },
  benchmark: {
    es: {
      panelHeading: 'Cómo te comparas',
      respondentCount: (n: number) =>
        `Basado en ${n.toLocaleString()} profesionales que tomaron este quiz`,
      overallLabel: 'Ranking general',
      countryLabel: (name: string) => `Tu país (${name})`,
      companyLabel: (name: string) => `Tu tipo de empresa (${name})`,
      industryLabel: (name: string) => `Tu industria (${name})`,
      percentileText: (pct: number, segment: string) =>
        `Puntuaste más alto que el ${pct}% de los encuestados ${segment}`,
      notEnoughData: 'Aún no hay suficientes datos — ¡sé de los primeros!',
      teaserHeading: 'Ve el panorama completo',
      teaserBody:
        '3 preguntas rápidas. Luego te mostramos dónde estás entre profesionales en tu rol, país e industria — y qué están haciendo ya las personas un nivel por delante de ti.',
      teaserCta: 'Muéstrame dónde estoy →',
      teaserSkip: 'Saltar — solo quiero ver mis resultados',
      teaserLockLabel: 'Tu benchmark está esperando',
      teaserLockSub: 'Responde 3 preguntas rápidas para desbloquearlo',
      calculating: 'Calculando tu benchmark...',
    },
    en: {
      panelHeading: 'How you compare',
      respondentCount: (n: number) =>
        `Based on ${n.toLocaleString()} professionals who've taken this quiz`,
      overallLabel: 'Overall ranking',
      countryLabel: (name: string) => `Your country (${name})`,
      companyLabel: (name: string) => `Your company type (${name})`,
      industryLabel: (name: string) => `Your industry (${name})`,
      percentileText: (pct: number, segment: string) =>
        `You scored higher than ${pct}% of all respondents ${segment}`,
      notEnoughData: 'Not enough data yet — be one of the first!',
      teaserHeading: 'See the full picture',
      teaserBody:
        "3 quick questions. Then we'll show you where you stand among professionals in your role, country, and industry — and what the people one level ahead are already doing.",
      teaserCta: 'Show me where I stand →',
      teaserSkip: 'Skip — I just want my results',
      teaserLockLabel: 'Your benchmark is waiting',
      teaserLockSub: 'Answer 3 quick questions to unlock it',
      calculating: 'Calculating your benchmark...',
    },
  },
  saveAndBenchmark: {
    es: {
      signInCtaTitle: 'Mira cómo te comparas',
      signInCtaBody:
        'Inicia sesión para guardar tu resultado y desbloquear tu benchmark contra el resto de la comunidad.',
      signInCtaButton: 'Inicia sesión para ver',
      saving: 'Guardando…',
      error: 'No pudimos guardar tu resultado.',
      retry: 'Reintentar',
      globalBenchmarkLine: (pct: number) => `Puntuaste más alto que el ${pct}% de los encuestados`,
      globalBenchmarkRespondents: (n: number) =>
        `Basado en ${n.toLocaleString()} profesionales que tomaron este quiz`,
    },
    en: {
      signInCtaTitle: 'See how you compare',
      signInCtaBody:
        'Sign in to save your result and unlock your benchmark against the rest of the community.',
      signInCtaButton: 'Sign in to unlock',
      saving: 'Saving…',
      error: "Couldn't save your result.",
      retry: 'Retry',
      globalBenchmarkLine: (pct: number) => `You scored higher than ${pct}% of respondents`,
      globalBenchmarkRespondents: (n: number) =>
        `Based on ${n.toLocaleString()} professionals who've taken this quiz`,
    },
  },
  auth: {
    es: {
      login: {
        title: 'Inicia sesión',
        subtitle: 'Accede a tu cuenta para ver tus resultados.',
        emailLabel: 'Email',
        emailPlaceholder: 'tu@email.com',
        passwordLabel: 'Contraseña',
        passwordPlaceholder: 'Tu contraseña',
        submit: 'Entrar',
        submitting: 'Entrando...',
        forgot: '¿Olvidaste tu contraseña?',
        switchPrompt: '¿No tienes cuenta?',
        switchCta: 'Regístrate',
      },
      signup: {
        title: 'Crea tu cuenta',
        subtitle: 'Guarda tus resultados y compáralos con la comunidad.',
        nameLabel: 'Nombre',
        namePlaceholder: 'Tu nombre',
        emailLabel: 'Email',
        emailPlaceholder: 'tu@email.com',
        passwordLabel: 'Contraseña',
        passwordPlaceholder: 'Mínimo 8 caracteres',
        confirmLabel: 'Confirma la contraseña',
        confirmPlaceholder: 'Repite la contraseña',
        submit: 'Crear cuenta',
        submitting: 'Creando cuenta...',
        switchPrompt: '¿Ya tienes cuenta?',
        switchCta: 'Inicia sesión',
      },
      forgot: {
        title: 'Recupera tu contraseña',
        subtitle: 'Te enviaremos un enlace para restablecerla.',
        emailLabel: 'Email',
        emailPlaceholder: 'tu@email.com',
        submit: 'Enviar enlace',
        submitting: 'Enviando...',
        back: '← Volver al inicio de sesión',
      },
      checkEmail: {
        signupTitle: 'Confirma tu correo',
        signupBody:
          'Te enviamos un correo a {email}. Haz click en el enlace para confirmar tu cuenta.',
        resetTitle: 'Revisa tu bandeja',
        resetBody:
          'Si tienes una cuenta con {email}, te enviamos un enlace para restablecer tu contraseña.',
        close: 'Listo',
      },
      signupDemographics: {
        title: 'Cuéntanos un poco más',
        subtitle:
          'Es opcional, pero nos ayuda a mostrarte cómo te comparas con personas en tu país, industria y rango salarial.',
        save: 'Guardar y continuar',
        saving: 'Guardando…',
        skip: 'Saltar por ahora',
        loading: 'Cargando opciones…',
        emptyOption: '—',
      },
      reset: {
        title: 'Define tu nueva contraseña',
        subtitle: 'Ingresa una contraseña nueva para tu cuenta.',
        passwordLabel: 'Nueva contraseña',
        passwordPlaceholder: 'Mínimo 8 caracteres',
        confirmLabel: 'Confirma la contraseña',
        confirmPlaceholder: 'Repite la contraseña',
        submit: 'Guardar y continuar',
        submitting: 'Guardando...',
      },
      logout: 'Cerrar sesión',
      loginCta: 'Iniciar sesión',
      errors: {
        invalidEmail: 'Ingresa un email válido.',
        passwordTooShort: 'La contraseña debe tener al menos 8 caracteres.',
        passwordMismatch: 'Las contraseñas no coinciden.',
        nameRequired: 'Ingresa tu nombre.',
        invalidCredentials: 'Email o contraseña incorrectos.',
        emailExists: 'Ese email ya está registrado.',
        emailNotConfirmed: 'Confirma tu correo antes de iniciar sesión.',
        rateLimited: 'Demasiados intentos. Intenta de nuevo en unos minutos.',
        weakPassword: 'La contraseña es demasiado débil.',
        sameOrigin: 'La nueva contraseña debe ser distinta de la actual.',
        generic: 'Algo salió mal. Intenta de nuevo.',
        sessionExpired: 'El enlace expiró. Solicita uno nuevo.',
      },
      resend: {
        prompt: '¿No recibiste el correo?',
        cta: 'Reenviar confirmación',
        sent: 'Reenviado.',
      },
    },
    en: {
      login: {
        title: 'Sign in',
        subtitle: 'Access your account to see your results.',
        emailLabel: 'Email',
        emailPlaceholder: 'you@email.com',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Your password',
        submit: 'Sign in',
        submitting: 'Signing in...',
        forgot: 'Forgot your password?',
        switchPrompt: "Don't have an account?",
        switchCta: 'Sign up',
      },
      signup: {
        title: 'Create your account',
        subtitle: 'Save your results and compare with the community.',
        nameLabel: 'Name',
        namePlaceholder: 'Your name',
        emailLabel: 'Email',
        emailPlaceholder: 'you@email.com',
        passwordLabel: 'Password',
        passwordPlaceholder: 'At least 8 characters',
        confirmLabel: 'Confirm password',
        confirmPlaceholder: 'Repeat your password',
        submit: 'Create account',
        submitting: 'Creating account...',
        switchPrompt: 'Already have an account?',
        switchCta: 'Sign in',
      },
      forgot: {
        title: 'Reset your password',
        subtitle: "We'll send you a link to reset it.",
        emailLabel: 'Email',
        emailPlaceholder: 'you@email.com',
        submit: 'Send link',
        submitting: 'Sending...',
        back: '← Back to sign in',
      },
      checkEmail: {
        signupTitle: 'Confirm your email',
        signupBody: 'We sent an email to {email}. Click the link to confirm your account.',
        resetTitle: 'Check your inbox',
        resetBody: "If an account exists for {email}, we've sent a link to reset your password.",
        close: 'Done',
      },
      signupDemographics: {
        title: 'Tell us a bit more',
        subtitle:
          'Optional, but it helps us show you how you compare to people in your country, industry, and salary range.',
        save: 'Save and continue',
        saving: 'Saving…',
        skip: 'Skip for now',
        loading: 'Loading options…',
        emptyOption: '—',
      },
      reset: {
        title: 'Set your new password',
        subtitle: 'Enter a new password for your account.',
        passwordLabel: 'New password',
        passwordPlaceholder: 'At least 8 characters',
        confirmLabel: 'Confirm password',
        confirmPlaceholder: 'Repeat your password',
        submit: 'Save and continue',
        submitting: 'Saving...',
      },
      logout: 'Sign out',
      loginCta: 'Sign in',
      errors: {
        invalidEmail: 'Please enter a valid email.',
        passwordTooShort: 'Password must be at least 8 characters.',
        passwordMismatch: 'Passwords do not match.',
        nameRequired: 'Please enter your name.',
        invalidCredentials: 'Wrong email or password.',
        emailExists: 'That email is already registered.',
        emailNotConfirmed: 'Please confirm your email before signing in.',
        rateLimited: 'Too many attempts. Try again in a few minutes.',
        weakPassword: 'Password is too weak.',
        sameOrigin: 'New password must differ from the current one.',
        generic: 'Something went wrong. Please try again.',
        sessionExpired: 'The link has expired. Request a new one.',
      },
      resend: {
        prompt: "Didn't get the email?",
        cta: 'Resend confirmation',
        sent: 'Sent again.',
      },
    },
  },
} as const;
