export type Tool = { emoji: string; name: string };

export const ROW_1: Tool[] = [
  { emoji: "🤖", name: "Claude" },
  { emoji: "💬", name: "ChatGPT" },
  { emoji: "✨", name: "Gemini" },
  { emoji: "🔍", name: "Perplexity" },
  { emoji: "⚡", name: "Grok" },
  { emoji: "💻", name: "Cursor" },
  { emoji: "🏄", name: "Windsurf" },
  { emoji: "🐙", name: "GitHub Copilot" },
  { emoji: "🔧", name: "Replit" },
  { emoji: "🎨", name: "v0" },
  { emoji: "💜", name: "Lovable" },
  { emoji: "⚡", name: "Bolt" },
  { emoji: "⚙️", name: "Make" },
  { emoji: "🔗", name: "Zapier" },
  { emoji: "🔀", name: "n8n" },
  { emoji: "🤝", name: "Manus" },
  { emoji: "🖼️", name: "Midjourney" },
  { emoji: "🎨", name: "DALL-E 3" },
  { emoji: "✏️", name: "Canva AI" },
  { emoji: "🔥", name: "Adobe Firefly" },
  { emoji: "💡", name: "Ideogram" },
  { emoji: "🌊", name: "Flux" },
  { emoji: "🎬", name: "Runway" },
  { emoji: "🎥", name: "HeyGen" },
  { emoji: "👤", name: "Synthesia" },
];

export const ROW_2: Tool[] = [
  { emoji: "🎙️", name: "ElevenLabs" },
  { emoji: "🎵", name: "Suno" },
  { emoji: "🎶", name: "Udio" },
  { emoji: "🔊", name: "Whisper" },
  { emoji: "🎞️", name: "Kling" },
  { emoji: "🌀", name: "Sora" },
  { emoji: "📹", name: "Veo 2" },
  { emoji: "📝", name: "Granola" },
  { emoji: "🔥", name: "Fireflies.ai" },
  { emoji: "🦦", name: "Otter.ai" },
  { emoji: "📋", name: "Notion AI" },
  { emoji: "📅", name: "Motion" },
  { emoji: "📧", name: "Superhuman" },
  { emoji: "🎯", name: "Gamma" },
  { emoji: "💎", name: "Beautiful.ai" },
  { emoji: "📖", name: "Tome" },
  { emoji: "📚", name: "NotebookLM" },
  { emoji: "🖥️", name: "Framer AI" },
  { emoji: "🌐", name: "Webflow AI" },
  { emoji: "🏗️", name: "Durable" },
  { emoji: "📊", name: "Julius AI" },
  { emoji: "🧠", name: "Perplexity Deep Research" },
  { emoji: "🔬", name: "ChatGPT Deep Research" },
  { emoji: "📡", name: "Claude Deep Research" },
  { emoji: "🎧", name: "NotebookLM Audio" },
];
