// One-off generator: reads lib/* and emits supabase/seed.sql.
// Run with: node --experimental-strip-types scripts/generate-seed.ts
// (Node 24+; outputs to ./supabase/seed.sql.)

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { LEVEL_LABELS, QUESTIONS, RESULT_COPY } from '../lib/content.ts';
import { COMPANY_QUESTIONS } from '../lib/companyAssessment.ts';
import { COMPANY_RESULT_COPY } from '../lib/companyResults.ts';
import { ROLE_ASSESSMENTS } from '../lib/roles.ts';
import { ROLE_RESULT_COPY } from '../lib/roleResults.ts';

type Locale = 'es' | 'en';

function sqlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

const out: string[] = [];
out.push('-- AUTO-GENERATED by scripts/generate-seed.ts. Do not edit by hand.');
out.push('-- Re-run the generator and commit the resulting SQL.');
out.push('');
out.push('begin;');
out.push('');

// Truncate so seed is idempotent (cascade hits responses + demographics).
out.push(`truncate table public.quiz_attempt_demographics restart identity cascade;`);
out.push(`truncate table public.quiz_responses restart identity cascade;`);
out.push(`truncate table public.quiz_attempts restart identity cascade;`);
out.push(`truncate table public.quiz_insights restart identity cascade;`);
out.push(`truncate table public.result_band_copies cascade;`);
out.push(`truncate table public.question_translations cascade;`);
out.push(`truncate table public.questions restart identity cascade;`);
out.push(`truncate table public.question_tier_translations cascade;`);
out.push(`truncate table public.question_tiers restart identity cascade;`);
out.push(`truncate table public.demographic_option_translations cascade;`);
out.push(`truncate table public.demographic_options restart identity cascade;`);
out.push(`truncate table public.demographic_field_translations cascade;`);
out.push(`truncate table public.demographic_fields restart identity cascade;`);
out.push(`truncate table public.quizzes restart identity cascade;`);
out.push('');

interface QuizSpec {
  slug: string;
  // Questions in DB sort_order: kept identical to the array order in lib/.
  questions: Array<{
    level: number;
    es: string;
    en: string;
  }>;
  // Per-level tier labels. Index 0..4.
  tierLabels: Array<{ es: string; en: string }>;
  // 5 result bands, ordinal 0..4.
  resultBands: Array<{
    description: { es: string; en: string };
    nextStep: { es: string; en: string };
  }>;
}

function generalSpec(): QuizSpec {
  return {
    slug: 'general',
    questions: QUESTIONS.map((q) => ({ level: q.level, es: q.es, en: q.en })),
    tierLabels: LEVEL_LABELS.map((l) => ({ es: l.es, en: l.en })),
    resultBands: RESULT_COPY,
  };
}

function companySpec(): QuizSpec {
  // Company questions carry their own per-level levelLabel; pick first per level.
  const tierLabels: Array<{ es: string; en: string }> = [];
  for (let lvl = 0; lvl < 5; lvl++) {
    const found = COMPANY_QUESTIONS.find((q) => q.level === lvl);
    if (!found) throw new Error(`Company quiz missing level ${lvl}`);
    tierLabels[lvl] = { es: found.levelLabel.es, en: found.levelLabel.en };
  }
  return {
    slug: 'company',
    questions: COMPANY_QUESTIONS.map((q) => ({
      level: q.level,
      es: q.statement.es,
      en: q.statement.en,
    })),
    tierLabels,
    resultBands: COMPANY_RESULT_COPY,
  };
}

function roleSpecs(): QuizSpec[] {
  return Object.values(ROLE_ASSESSMENTS).map((ra) => {
    const tierLabels: Array<{ es: string; en: string }> = [];
    for (let lvl = 0; lvl < 5; lvl++) {
      const found = ra.questions.find((q) => q.level === lvl);
      if (!found) throw new Error(`Role ${ra.roleId} missing level ${lvl}`);
      tierLabels[lvl] = { es: found.levelLabel.es, en: found.levelLabel.en };
    }
    return {
      slug: `role-${ra.roleId}`,
      questions: ra.questions.map((q) => ({
        level: q.level,
        es: q.statement.es,
        en: q.statement.en,
      })),
      tierLabels,
      resultBands: ROLE_RESULT_COPY,
    };
  });
}

const specs: QuizSpec[] = [generalSpec(), companySpec(), ...roleSpecs()];

// Inserts use a CTE that resolves quiz_id and tier_id by slug+ordinal so we
// don't have to hand-pin UUIDs.
for (const spec of specs) {
  out.push(`-- ─── ${spec.slug} ─────────────────────────────────────────────────────`);
  out.push(`insert into public.quizzes (slug, is_active) values (${sqlString(spec.slug)}, true);`);

  // Tiers
  for (let i = 0; i < spec.tierLabels.length; i++) {
    out.push(
      `insert into public.question_tiers (quiz_id, ordinal, sort_order) ` +
        `select id, ${i}, ${i} from public.quizzes where slug = ${sqlString(spec.slug)};`,
    );
  }

  // Tier translations
  for (let i = 0; i < spec.tierLabels.length; i++) {
    const tl = spec.tierLabels[i]!;
    for (const locale of ['es', 'en'] as Locale[]) {
      out.push(
        `insert into public.question_tier_translations (tier_id, locale, short_label) ` +
          `select t.id, ${sqlString(locale)}, ${sqlString(tl[locale])} ` +
          `from public.question_tiers t ` +
          `join public.quizzes q on q.id = t.quiz_id ` +
          `where q.slug = ${sqlString(spec.slug)} and t.ordinal = ${i};`,
      );
    }
  }

  // Questions + translations
  for (let idx = 0; idx < spec.questions.length; idx++) {
    const q = spec.questions[idx]!;
    out.push(
      `with ins as (` +
        `insert into public.questions (quiz_id, tier_id, sort_order, weight, is_active) ` +
        `select q.id, t.id, ${idx}, 1, true ` +
        `from public.quizzes q ` +
        `join public.question_tiers t on t.quiz_id = q.id and t.ordinal = ${q.level} ` +
        `where q.slug = ${sqlString(spec.slug)} returning id` +
        `) ` +
        `insert into public.question_translations (question_id, locale, statement) ` +
        `select id, 'es', ${sqlString(q.es)} from ins ` +
        `union all select id, 'en', ${sqlString(q.en)} from ins;`,
    );
  }

  // Result band copies
  for (let band = 0; band < spec.resultBands.length; band++) {
    const rb = spec.resultBands[band]!;
    for (const locale of ['es', 'en'] as Locale[]) {
      out.push(
        `insert into public.result_band_copies (quiz_id, ordinal, locale, description, next_step) ` +
          `select id, ${band}, ${sqlString(locale)}, ${sqlString(rb.description[locale])}, ${sqlString(rb.nextStep[locale])} ` +
          `from public.quizzes where slug = ${sqlString(spec.slug)};`,
      );
    }
  }

  out.push('');
}

out.push('commit;');
out.push('');

const outputPath = resolve(import.meta.dirname, '..', 'supabase', 'seed.sql');
writeFileSync(outputPath, out.join('\n'));
console.log(`Wrote ${outputPath} (${out.length} lines, ${specs.length} quizzes).`);
